# analysis_options.yaml

# Basierend auf den offiziellen Flutter-Lints
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .dart_tool/**
    - build/**
    - lib/generated_plugin_registrant.dart

  errors:
    override_on_non_overriding_member: ignore
    use_build_context_synchronously:      ignore
    unnecessary_cast:                     ignore
    deprecated_member_use:                ignore  # z. B. .withOpacity(), .background(), etc.
    unused_import:                        ignore  # z. B. 'dart:math'

linter:
  rules:
    avoid_print:                             false
    use_super_parameters:                    false
    library_private_types_in_public_api:     false
    prefer_interpolation_to_compose_strings: false