name: tapem
description: "Tap’em – NFC-basiertes Gym-Tracking und Gym-Management"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  collection: ^1.17.0

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0

  # Lokalisierung
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State-Management & Utilities
  provider: ^6.1.5
  uuid: ^4.5.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_crashlytics: ^4.3.5

  # Charts & Kalender
  fl_chart: ^1.0.0
  table_calendar: ^3.1.3
  flutter_heatmap_calendar: ^1.0.5

  # Weitere Helfer
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.9.0
  url_launcher: ^6.1.7

  # Local Storage
  shared_preferences: ^2.4.10

  nfc_manager: ^4.0.2
  nfc_manager_ndef:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      path: packages/nfc_manager_ndef
  ndef_record: ^1.2.1
  

  # NFC: nur flutter_nfc_kit in Version, die zu eurem Flutter passt
  flutter_nfc_kit: ^3.6.0
  ndef: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.14.3

# Icon-Konfiguration
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/logo.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/logos/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales:
    - de
    - en
