name: tapem
description: "Tap’em – NFC-basiertes Gym-Tracking und Gym-Management"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0" # passend zu Dart 3.8.1 (Flutter 3.32.8)

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  collection: ^1.17.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_sticky_header: ^0.7.0
  scrollable_positioned_list: ^0.3.5
  google_fonts: ^6.1.0

  # Lokalisierung
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State-Management & Utilities
  provider: ^6.1.5
  uuid: ^4.5.1
  csv: ^6.0.0
  googleapis: ^14.0.0 # nur falls wirklich benötigt
  file_picker: ^10.2.0
  async: ^2.11.0

  # Firebase (stabile, bereits verwendete Major-Versionen)
  firebase_core: ^3.15.2
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.6.1
  firebase_storage: ^12.0.3
  firebase_messaging: ^15.2.10
  firebase_app_check: ^0.3.2+10
  firebase_remote_config: ^5.0.5
  # HINWEIS: firebase_dynamic_links ist eingestellt -> entfernt. Später ggf. auf Universal Links migrieren.

  # Charts & Kalender
  fl_chart: ^1.0.0
  table_calendar: ^3.1.3
  flutter_cube: ^0.1.1
  flutter_heatmap_calendar: ^1.0.5
  vector_math: ^2.1.4
  flutter_colorpicker: ^1.0.3
  flutter_svg: ^1.1.6
  model_viewer_plus: ^1.0.7

  # Weitere Helfer
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.9.0
  url_launcher: ^6.1.7

  # Local Storage & Timezone
  shared_preferences: ^2.4.10
  flutter_timezone: ^4.1.1

  # NFC-Pakete (Git-Quelle für Fixes)
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      path: packages/nfc_manager
  nfc_manager_ndef:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      path: packages/nfc_manager_ndef
  ndef_record: ^1.2.1
  flutter_nfc_kit: ^3.6.0
  ndef: ^0.3.4
  firebase_dynamic_links: 6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.14.3
  fake_cloud_firestore: ^3.1.0
  mocktail: ^1.0.0
  url_launcher_platform_interface: any

# Overrides (behalten, damit nfc_manager konsistent aus Git kommt;
# value_layout_builder ist erforderlich für aktuelle Abhängigkeiten)
dependency_overrides:
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      path: packages/nfc_manager
  value_layout_builder: ^0.5.0

# Icon-Konfiguration
flutter_icons:
  android: true
  ios: true
  image_path: assets/logos/logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/logo.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/logos/
    - assets/models/
    - assets/models/body.gltf
    - assets/muscle_heatmap.svg
    - assets/body_front.svg
    - assets/body_back.svg
    - assets/avatars/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales:
    - de
    - en
