name: tapem
description: "Tap’em – NFC-basiertes Gym-Tracking und Gym-Management"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  collection: ^1.17.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_sticky_header: ^0.6.5
  scrollable_positioned_list: ^0.3.5
  google_fonts: ^6.1.0

  # Lokalisierung
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State-Management & Utilities
  provider: ^6.1.5
  uuid: ^4.5.1
  csv: ^6.0.0
  googleapis: ^14.0.0     # Nur falls du wirklich die Sheets-API nutzt
  # google_sign_in: ^6.2.1
  async: ^2.11.0

  # Firebase
  firebase_auth: ^5.5.3
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.7
  cloud_functions: ^5.6.1
  firebase_storage: ^12.0.3
  firebase_dynamic_links: ^6.1.10

  # Charts & Kalender
  fl_chart: ^1.0.0
  table_calendar: ^3.1.3
  flutter_cube: ^0.1.1
  flutter_heatmap_calendar: ^1.0.5
  vector_math: ^2.1.4
  flutter_colorpicker: ^1.0.3

  # Weitere Helfer
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.9.0
  url_launcher: ^6.1.7

  # Local Storage
  shared_preferences: ^2.4.10

  # NFC-Pakete (aus Git für Threading-Fix)
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      path: packages/nfc_manager
  nfc_manager_ndef:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      path: packages/nfc_manager_ndef
  ndef_record: ^1.2.1
  flutter_nfc_kit: ^3.6.0
  ndef: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  flutter_launcher_icons: ^0.14.3

# Dependency overrides to ensure both packages use the git source
dependency_overrides:
  nfc_manager:
    git:
      url: https://github.com/okadan/flutter-nfc-manager.git
      path: packages/nfc_manager

# Icon-Konfiguration
flutter_icons:
  android: true
  ios: true
  image_path: assets/logos/logo.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/logo.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/logos/
    - assets/models/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations
  preferred-supported-locales:
    - de
    - en