// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC851f99faMrOl5L44v7rph3bRlxhq5HQs',
    appId: '1:397332415566:web:bac0d0267c8895a7a12f1f',
    messagingSenderId: '397332415566',
    projectId: 'tap-em-dev',
    authDomain: 'tap-em-dev.firebaseapp.com',
    storageBucket: 'tap-em-dev.firebasestorage.app',
    measurementId: 'G-45GPC2BS6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKccs8AdC1ftuXrEHOlF4Mkvdpd-XMdCk',
    appId: '1:397332415566:android:8fe5606571cabcb7a12f1f',
    messagingSenderId: '397332415566',
    projectId: 'tap-em-dev',
    storageBucket: 'tap-em-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3ob7jwi7B-1uyPeRVFPLCLuo5y0TtVI8',
    appId: '1:397332415566:ios:99fd94ba38bfe0a3a12f1f',
    messagingSenderId: '397332415566',
    projectId: 'tap-em-dev',
    storageBucket: 'tap-em-dev.firebasestorage.app',
    iosBundleId: 'com.example.tapem.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3ob7jwi7B-1uyPeRVFPLCLuo5y0TtVI8',
    appId: '1:397332415566:ios:7ce650d319befaa4a12f1f',
    messagingSenderId: '397332415566',
    projectId: 'tap-em-dev',
    storageBucket: 'tap-em-dev.firebasestorage.app',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC851f99faMrOl5L44v7rph3bRlxhq5HQs',
    appId: '1:397332415566:web:51c068826c357a82a12f1f',
    messagingSenderId: '397332415566',
    projectId: 'tap-em-dev',
    authDomain: 'tap-em-dev.firebaseapp.com',
    storageBucket: 'tap-em-dev.firebasestorage.app',
    measurementId: 'G-CSST2XPHRB',
  );
}
