// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XAwxRZw_bIs3FnNAhIh7w8qfKBsN5jE',
    appId: '1:380604353667:web:9d335198cb76ac4e229fb6',
    messagingSenderId: '380604353667',
    projectId: 'tap-em',
    authDomain: 'tap-em.firebaseapp.com',
    storageBucket: 'tap-em.firebasestorage.app',
    measurementId: 'G-9ZQBL22Y4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNYRaw6lq3tqaIYZaHsrJ5phtXKFiMaSc',
    appId: '1:380604353667:android:5a372976ec3f319b229fb6',
    messagingSenderId: '380604353667',
    projectId: 'tap-em',
    storageBucket: 'tap-em.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx1f8Y6CaRoWBEfmAJzdIIALd0Hfg6x9c',
    appId: '1:380604353667:ios:c8884bfd4535e40b229fb6',
    messagingSenderId: '380604353667',
    projectId: 'tap-em',
    storageBucket: 'tap-em.firebasestorage.app',
    iosBundleId: 'com.example.tapem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx1f8Y6CaRoWBEfmAJzdIIALd0Hfg6x9c',
    appId: '1:380604353667:ios:a95146712a872c6a229fb6',
    messagingSenderId: '380604353667',
    projectId: 'tap-em',
    storageBucket: 'tap-em.firebasestorage.app',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6XAwxRZw_bIs3FnNAhIh7w8qfKBsN5jE',
    appId: '1:380604353667:web:b4ce825dd3bd8162229fb6',
    messagingSenderId: '380604353667',
    projectId: 'tap-em',
    authDomain: 'tap-em.firebaseapp.com',
    storageBucket: 'tap-em.firebasestorage.app',
    measurementId: 'G-XKMGD0M4HG',
  );
}
