name: Security - Gitleaks
on:
  pull_request:
  push:
    branches: [ main, a_gpt5 ]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --config .gitleaks.toml --report-path gitleaks-report.json --report-format json
      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gitleaks-report
          path: gitleaks-report.json
