name: iOS TestFlight
on:
  workflow_dispatch:
jobs:
  build-upload:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: CocoaPods
        run: |
          sudo gem install cocoapods || true
          pod repo update
      - name: Flutter pub get
        run: flutter pub get
      - name: Build IPA
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install fastlane
        run: gem install fastlane
      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.ASC_KEY_P8_BASE64 }}
        run: |
          cd ios
          fastlane pilot upload \
            --api_key_path ./fastlane/api_key.json \
            --ipa "../build/ios/ipa/*.ipa" \
            --skip_waiting_for_build_processing true

